/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gluster/anthill/pkg/apis/anthill/v1alpha1"
	scheme "github.com/gluster/anthill/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlusterClustersGetter has a method to return a GlusterClusterInterface.
// A group's client should implement this interface.
type GlusterClustersGetter interface {
	GlusterClusters(namespace string) GlusterClusterInterface
}

// GlusterClusterInterface has methods to work with GlusterCluster resources.
type GlusterClusterInterface interface {
	Create(*v1alpha1.GlusterCluster) (*v1alpha1.GlusterCluster, error)
	Update(*v1alpha1.GlusterCluster) (*v1alpha1.GlusterCluster, error)
	UpdateStatus(*v1alpha1.GlusterCluster) (*v1alpha1.GlusterCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GlusterCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.GlusterClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GlusterCluster, err error)
	GlusterClusterExpansion
}

// glusterClusters implements GlusterClusterInterface
type glusterClusters struct {
	client rest.Interface
	ns     string
}

// newGlusterClusters returns a GlusterClusters
func newGlusterClusters(c *GlusterV1alpha1Client, namespace string) *glusterClusters {
	return &glusterClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the glusterCluster, and returns the corresponding glusterCluster object, and an error if there is any.
func (c *glusterClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.GlusterCluster, err error) {
	result = &v1alpha1.GlusterCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("glusterclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlusterClusters that match those selectors.
func (c *glusterClusters) List(opts v1.ListOptions) (result *v1alpha1.GlusterClusterList, err error) {
	result = &v1alpha1.GlusterClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("glusterclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested glusterClusters.
func (c *glusterClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("glusterclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a glusterCluster and creates it.  Returns the server's representation of the glusterCluster, and an error, if there is any.
func (c *glusterClusters) Create(glusterCluster *v1alpha1.GlusterCluster) (result *v1alpha1.GlusterCluster, err error) {
	result = &v1alpha1.GlusterCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("glusterclusters").
		Body(glusterCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a glusterCluster and updates it. Returns the server's representation of the glusterCluster, and an error, if there is any.
func (c *glusterClusters) Update(glusterCluster *v1alpha1.GlusterCluster) (result *v1alpha1.GlusterCluster, err error) {
	result = &v1alpha1.GlusterCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("glusterclusters").
		Name(glusterCluster.Name).
		Body(glusterCluster).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *glusterClusters) UpdateStatus(glusterCluster *v1alpha1.GlusterCluster) (result *v1alpha1.GlusterCluster, err error) {
	result = &v1alpha1.GlusterCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("glusterclusters").
		Name(glusterCluster.Name).
		SubResource("status").
		Body(glusterCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the glusterCluster and deletes it. Returns an error if one occurs.
func (c *glusterClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("glusterclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *glusterClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("glusterclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched glusterCluster.
func (c *glusterClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GlusterCluster, err error) {
	result = &v1alpha1.GlusterCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("glusterclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
