/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	anthill_v1alpha1 "github.com/gluster/anthill/pkg/apis/anthill/v1alpha1"
	versioned "github.com/gluster/anthill/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gluster/anthill/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/gluster/anthill/pkg/client/listers/anthill/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GlusterClusterInformer provides access to a shared informer and lister for
// GlusterClusters.
type GlusterClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GlusterClusterLister
}

type glusterClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGlusterClusterInformer constructs a new informer for GlusterCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGlusterClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGlusterClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGlusterClusterInformer constructs a new informer for GlusterCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGlusterClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GlusterV1alpha1().GlusterClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GlusterV1alpha1().GlusterClusters(namespace).Watch(options)
			},
		},
		&anthill_v1alpha1.GlusterCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *glusterClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGlusterClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *glusterClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&anthill_v1alpha1.GlusterCluster{}, f.defaultInformer)
}

func (f *glusterClusterInformer) Lister() v1alpha1.GlusterClusterLister {
	return v1alpha1.NewGlusterClusterLister(f.Informer().GetIndexer())
}
